services:
  db:
    image: mysql:9.3.0
    container_name: mysql-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u${MYSQL_USER} -p${MYSQL_PASSWORD}
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 60s

  budgetter-api:
    container_name: budgetter-api
    restart: always
    build:
      context: .
      dockerfile: ./docker/budgetter-api/Dockerfile
    volumes:
      - static_dist:/vol/www/static
      - ./docker/budgetter-api/apache.conf:/etc/apache2/sites-available/000-default.conf:ro
    depends_on:
      db:
        condition: service_healthy
    environment:
      - STATIC_ROOT=/vol/www/static
    env_file:
      - .env
      - .env.budgetter-api

  budgetter-front:
    container_name: budgetter-front
    build:
      context: .
      dockerfile: ./docker/budgetter-front/Dockerfile
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://budgetter-api
    volumes:
      - nuxt_dist:/vol/www/nuxt

  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_dist:/vol/www/static
      - nuxt_dist:/vol/www/nuxt
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - budgetter-api
      - budgetter-front

volumes:
  mysql_data:
  static_dist:
  nuxt_dist:
