server {
    listen 80;
    server_name localhost;

    location /budgetter/ {
        alias /vol/www/nuxt/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /static/ {
        alias /vol/www/static/;
        autoindex off;
    }

    location / {
        proxy_pass http://budgetter-api;
    }
}
