# Generated by Django 5.2.1 on 2025-05-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_loanrecord_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
